name: Build Pterodactyl Egg Container Image

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on:
  push:
    branches:
      - "master"

jobs:
  docker-build-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    strategy:
      fail-fast: false
      matrix:
        image: ["pumpkin-prebuilt", "pumpkin-shell"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub CR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Lowercase for image tagging
        run: |
          echo "REPO=${GITHUB_REPOSITORY@L}" >> "${GITHUB_ENV}"

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          file: ${{ matrix.image }}/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REPO }}:${{ matrix.image }}
